### ISSUE TITLE
জাভাস্ক্রিপ্টঃ ব্যাসিক ফাংশন

### ISSUE THREAD

**Issue by mhassain** [zonayedpca/old.js.zonayed.me#2]
সমস্যা বিস্তারিতঃ
function sumMachine(a, b) {
    var sum = a + b;
    **return sum;**
}
console.log(sumMachine(2, 2));
console.log(sumMachine(4, 4));
You Said: আমরা উপরে যে ফাংশন ইউজ করে কন্সোলে কিছু লগ করিয়েছি সেটা কিন্ত কোনো ভ্যালু প্রডিউস করে নি। কারণ সেই ফাংশন থেকে কিছু রিটার্ণ করা হয়নি। (which is wrong)
****** But you returned sum******

**Comment by zonayedpca** [comment]
আমি এখানে **উপরে যে ফাংশন ইউজ করে কন্সোলে কিছু লগ করিয়েছি** বলতে আসলে আগে যে উদাহরণ দিয়ে কন্সোলে কিছু লগ করেছিলাম ```console.log``` দিয়ে সেটা বুঝিয়েছি... ঠিক এই ফাংশনটা না, যেটা আসলে কিছু কন্সোল লগ করেনি। বরং এটা ভ্যালু রিটার্ণ করেছে... এটা একটু কনফিউজিং হয়ে গেছে তবে ঠিক পরের লাইনগুলো পড়লেই ক্লিয়ার হয়ে যাবেন আশা করি...
