### ISSUE TITLE
জাভাস্ক্রিপ্ট অ্যাডভান্সঃ ইনহেরিট্যান্স (Inheritance)

### ISSUE THREAD

**Issue by toufiq-austcse** [zonayedpca/old.js.zonayed.me#3]
সমস্যা বিস্তারিতঃ
![capture](https://user-images.githubusercontent.com/22225639/49116159-f86adf00-f2c6-11e8-92eb-effec2b8d214.PNG)
এখন ধরি আরেকটা অবজেক্ট আছে Athlete নামে যেটা ঠিক Person এর সবগুলো ফিচারই থাকবে। 
এইটা কি ভাইয়া "Person এর সবগুলো ফিচারই থাকবে" হবে নাকি "GeneralPeople এর সবগুলো ফিচারই থাকবে" হবে? নিচের কোড টাতে তো  GeneralPeople ফাংশন কন্সট্রাকটরকে call করা হয়েছ ।
ধন্যবাদ ।

**Comment by zonayedpca** [comment]
ধন্যবাদ ভাইয়া... আমি পুরো আর্টিকেলটা রিভিও করে আপনাকে জানাচ্ছি...

**Comment by zonayedpca** [comment]
আবারো ধন্যবাদ ভাই... লেখা আপডেট করে দিয়েছি... 👍
