### ISSUE TITLE
জাভাস্ক্রিপ্টঃ কি, কেন, কখন?

### ISSUE THREAD

**Issue by ashikrnhq04** [zonayedpca/old.js.zonayed.me#4]
অনেকগুলো বানান ভুল পেয়েছি। আমি সুযোগ পেলে বিনাশ্রমে বানানগুলো সংশোধন করতে চাই :)

**Comment by zonayedpca** [comment]
আপনার ইচ্ছার জন্য ধন্যবাদ... আমি সব সংশোধন করে একটা ভার্শন তৈরী করছি অনেকদিন যাবত... আশা করি শীগ্রই দেখতে পাবেন...

**Comment by ashikrnhq04** [comment]
ধন্যবাদ ভাই
