### ISSUE TITLE
জাভাস্ক্রিপ্টঃ কোথায় এবং কিভাবে ইউজ করা হয়?

### ISSUE THREAD

**Issue by RabbiIslamRony** [zonayedpca/old.js.zonayed.me#5]
সমস্যা বিস্তারিতঃ
ekta banane sudhu matro vul hoise..
১। সহজঃ আপনার যে কাজ করতে বছর থেকবছর

**Comment by zonayedpca** [comment]
অনেক অনেক ধন্যবাদ... ফিক্স করে দিয়েছি...
