### ISSUE TITLE
জাভাস্ক্রিপ্ট অ্যাডভান্সঃ 

### ISSUE THREAD

**Issue by mahfuzdiu** [zonayedpca/old.js.zonayed.me#6]
![Capture](https://user-images.githubusercontent.com/43580524/62646602-7d3aec00-b970-11e9-9c08-9a71d5f8345e.PNG)

Brother this bind() doesn't work the way you have stated here. I have tried your code. It refers me to window object not that myCustomObj object. I will wait for your answer. 

Thank you.

**Comment by zonayedpca** [comment]
Let me check this thing again...

**Comment by zonayedpca** [comment]
It was my mistake and thanks for reporting this wrong thing as it was a little bit tricky to catch on. 

Yes, the output you are getting is absolutely right and it won't work as I have shown there. The corrected one should be like:

```javascript
var myCustomObj = {
   name: 'Zonayed Ahmed',
   age: 21,
   job: 'Student',
   anotherObj: {
      name: 'Ahmed Zonayed',
      value: function() {
         console.log(this);
      }
   }
}
```

And then: 

```javascript
myCustomObj.anotherObj.value.call(myCustomObj);
```

If you need more explanation why that one is not working, please refer to this StackOverflow post as it has also a similar type of problem: https://stackoverflow.com/questions/33932640/bind-this-of-parent-object-to-this-of-child-object-in-javascript

I have got another small problem in my blog on the very next post. But that one is although out of context. If you find any other problem please let me know as it helps my posts to be more accurate and helpful for the community. Sorry for my late response. I have updated all the posts now.
